name: zikzak_inappwebview_macos
description: macOS implementation of the zikzak_inappwebview plugin.
version: 4.0.4
homepage: https://inappwebview.dev/
repository: https://github.com/arrrrny/zikzak_inappwebview/tree/master/zikzak_inappwebview_macos
issue_tracker: https://github.com/arrrrny/zikzak_inappwebview/issues
topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_inappwebview_platform_interface: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  plugin_platform_interface: ^2.1.8

dependency_overrides:
  zikzak_inappwebview_platform_interface: ^4.0.4
  zikzak_inappwebview_internal_annotations: ^4.0.4

flutter:
  plugin:
    implements: zikzak_inappwebview
    platforms:
      macos:
        pluginClass: InAppWebViewFlutterPlugin
        dartPluginClass: MacOSInAppWebViewPlatform
