name: zikzak_inappwebview_macos
description: macOS implementation of the zikzak_inappwebview plugin.
version: 4.0.0
homepage: https://inappwebview.dev/
repository: https://github.com/arrrrny/zikzak_inappwebview/tree/master/zikzak_inappwebview_macos
issue_tracker: https://github.com/arrrrny/zikzak_inappwebview/issues
topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_inappwebview_platform_interface:
    path: ../zikzak_inappwebview_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    implements: zikzak_inappwebview
    platforms:
      macos:
        pluginClass: InAppWebViewFlutterPlugin
        dartPluginClass: MacOSInAppWebViewPlatform
