name: generators
version: 1.1.0

publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.5.0
  zikzak_inappwebview_internal_annotations:
    path: ../../zikzak_inappwebview_internal_annotations

dev_dependencies:
  build_runner: ^2.4.13
  build_test: ^2.2.2
  test: ^1.25.8
