name: zikzak_inappwebview_internal_annotations
description: Internal annotations used by the generator of zikzak_inappwebview plugin
version: 4.0.9
homepage: https://github.com/arrrrny/zikzak_inappwebview

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0
